//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlipperAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASPNETUSERCLAIMS
    {
        public int ID { get; set; }
        public string USERID { get; set; }
        public string CLAIMTYPE { get; set; }
        public string CLAIMVALUE { get; set; }
    }
}
