//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlipperAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<ACTORS> ACTORS { get; set; }
        public virtual DbSet<ASPNETROLES> ASPNETROLES { get; set; }
        public virtual DbSet<ASPNETUSERCLAIMS> ASPNETUSERCLAIMS { get; set; }
        public virtual DbSet<ASPNETUSERROLES> ASPNETUSERROLES { get; set; }
        public virtual DbSet<ASPNETUSERS> ASPNETUSERS { get; set; }
        public virtual DbSet<FIDELITY_BONUS> FIDELITY_BONUS { get; set; }
        public virtual DbSet<FILM_ACTOR> FILM_ACTOR { get; set; }
        public virtual DbSet<FILM_GENRE> FILM_GENRE { get; set; }
        public virtual DbSet<FILMS> FILMS { get; set; }
        public virtual DbSet<GENRES> GENRES { get; set; }
        public virtual DbSet<RESERVATIONS> RESERVATIONS { get; set; }
        public virtual DbSet<SCREENINGS> SCREENINGS { get; set; }
        public virtual DbSet<SEATS> SEATS { get; set; }
        public virtual DbSet<THEATERS> THEATERS { get; set; }
        public virtual DbSet<VW_FILM_CATALOG> VW_FILM_CATALOG { get; set; }
    }
}
