//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlipperAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVATIONS
    {
        public decimal ID_RESERVATION { get; set; }
        public decimal ID_SCREENING { get; set; }
        public Nullable<System.DateTime> RESERVATION_DATE { get; set; }
        public decimal ID_SEAT { get; set; }
        public string ID_USER { get; set; }
    
        public virtual ASPNETUSERS ASPNETUSERS { get; set; }
        public virtual SEATS SEATS { get; set; }
        public virtual SCREENINGS SCREENINGS { get; set; }
    }
}
