//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlipperAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCREENINGS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SCREENINGS()
        {
            this.RESERVATIONS = new HashSet<RESERVATIONS>();
        }
    
        public decimal ID_SCREENING { get; set; }
        public decimal ID_FILM { get; set; }
        public System.DateTime SCREENING_DATE { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public Nullable<byte> REDUCTION_PCT { get; set; }
        public Nullable<decimal> REDUCTED_PRICE { get; set; }
        public decimal ID_THEATER { get; set; }
    
        public virtual FILMS FILMS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESERVATIONS> RESERVATIONS { get; set; }
        public virtual THEATERS THEATERS { get; set; }
    }
}
