//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlipperAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_FILM_CATALOG
    {
        public string NOME { get; set; }
        public System.DateTime RILASCIATO { get; set; }
        public string TRAMA { get; set; }
        public string ATTORI { get; set; }
        public string CATEGORIA { get; set; }
    }
}
